In [31]:
#Categorical/Nomivnal value pre
import pandas;
from numpy import array
diabetesData = pandas.read_csv('Diabetes.csv')

from sklearn.preprocessing import OneHotEncoder
gender = array([diabetesData.sex])
enc = OneHotEncoder()
print(enc.fit_transform(gender))
genderData = pandas.DataFrame(enc.fit_transform(gender), columns=['male', 'female'])

dataX = pandas.DataFrame({'age': diabetesData.age, 'bmi': diabetesData.bmi \
                          , 'bp':diabetesData.bp, 's1': diabetesData.s1 \
                          , 's2':diabetesData.s2, 's3': diabetesData.s3 \
                          , 's4':diabetesData.s4, 's5': diabetesData.s5, 's6': diabetesData.s6
})




  (0, 441)	1.0
  (0, 440)	1.0
  (0, 439)	1.0
  (0, 438)	1.0
  (0, 437)	1.0
  (0, 436)	1.0
  (0, 435)	1.0
  (0, 434)	1.0
  (0, 433)	1.0
  (0, 432)	1.0
  (0, 431)	1.0
  (0, 430)	1.0
  (0, 429)	1.0
  (0, 428)	1.0
  (0, 427)	1.0
  (0, 426)	1.0
  (0, 425)	1.0
  (0, 424)	1.0
  (0, 423)	1.0
  (0, 422)	1.0
  (0, 421)	1.0
  (0, 420)	1.0
  (0, 419)	1.0
  (0, 418)	1.0
  (0, 417)	1.0
  :	:
  (0, 24)	1.0
  (0, 23)	1.0
  (0, 22)	1.0
  (0, 21)	1.0
  (0, 20)	1.0
  (0, 19)	1.0
  (0, 18)	1.0
  (0, 17)	1.0
  (0, 16)	1.0
  (0, 15)	1.0
  (0, 14)	1.0
  (0, 13)	1.0
  (0, 12)	1.0
  (0, 11)	1.0
  (0, 10)	1.0
  (0, 9)	1.0
  (0, 8)	1.0
  (0, 7)	1.0
  (0, 6)	1.0
  (0, 5)	1.0
  (0, 4)	1.0
  (0, 3)	1.0
  (0, 2)	1.0
  (0, 1)	1.0
  (0, 0)	1.0


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you us

ValueError: DataFrame constructor not properly called!

In [14]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
print('integer_encoded" ', integer_encoded)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]
integer_encoded"  [[0]
 [0]
 [2]
 [0]
 [1]
 [1]
 [2]
 [0]
 [2]
 [1]]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
['cold']


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
